version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
  api:
    container_name: "server"
    build: ./server/
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  pwa:
    container_name: "client"
    build: ./client/
    ports:
      - "3000:3000"
